Map Nodes = {
  'Ind': {
    'values': [
      'PID_Regulator_3_PreHeater2.sStartRegualtion',
      'PID_Regulator_3_PreHeater2.sActTemperature',
      'PID_Regulator_3_PreHeater2.sControlPowerOut',
      'PID_Regulator_3_PreHeater2.sFinalSetPoint',
      'PID_Regulator_3_PreHeater2.sAuxStepSetpoint',
    ],
    'titles': [
      'Start',
      'Temp',
      'Power out',
      'Setpont',
      'Auxstep',
    ],
    'widgetTypes': [
      0,
      1,
      3,
      2,
      1,
    ],
  },
  'PFR': {
    'values': [
      'PID_Regulator_1_PFR.sStartRegualtion',
      'PID_Regulator_1_PFR.sActTemperature',
      'PID_Regulator_1_PFR.sControlPowerOut',
      'PID_Regulator_1_PFR.sFinalSetPoint',
      'PID_Regulator_1_PFR.sAuxStepSetpoint',
    ],
    'titles': [
      'Start',
      'Temp',
      'Power out',
      'Setpont',
      'Auxstep',
    ],
    'widgetTypes': [
      0,
      1,
      3,
      2,
      1,
    ],
  },
  'H.E.': {
    'values': [
      'OutletCoolingWaterTempMonitor.sActTemperature',
      'InletCoolingWaterTempMonitor.sActTemperature',
      'InjectedFluidTemperatureMonitor.sActTemperature',
      'SafetyValveTempMonitor.sActTemperature',
    ],
    'titles': [
      'Out H2O',
      'In H2O',
      'In Slurry',
      'Safety V. T.',
    ],
    'widgetTypes': [
      1,
      1,
      1,
      1,
    ],
  },
  'O.H.': {
    'values': [
      'PID_Regulator_2_PreHeater1.sStartRegualtion',
      'PID_Regulator_2_PreHeater1.sActTemperature',
      'PID_Regulator_2_PreHeater1.sControlPowerOut',
      'PID_Regulator_2_PreHeater1.sFinalSetPoint',
      'PID_Regulator_2_PreHeater1.sAuxStepSetpoint',
    ],
    'titles': [
      'Start',
      'Temp',
      'Power out',
      'Setpont',
      'Auxstep',
    ],
    'widgetTypes': [
      0,
      1,
      3,
      2,
      1,
    ],
  },
  'Pmp_1': {
    'values': [
      'PumpMng1.sStartPump',
      // '',
      '',
      '_ReadWriteHoldingRegister1.sSetSafetyPressureA',
      '_ReadWriteHoldingRegister1.sSetSafetyPressureB',
      '_ReadWriteHoldingRegister1.sSetRateA',
      '_ReadWriteHoldingRegister1.sSetRateB',
    ],
    'titles': [
      'Start',
      // 'Set Pressure',
      'Reset errors',
      'Set safety P A',
      'Set safety P B',
      'Set Flow A',
      'Set Flow B',
    ],
    'widgetTypes': [
      0, 0,
      // 2,
      2, 2, 2, 2, 2,
    ],
  },
  'Pmp_2': {
    'values': [
      '_ReadInputRegister1.sPressure_OUT',
      '_ReadInputRegister1.SFlowTotal',
      '_ReadInputRegister1.SFlowCylinderA',
      '_ReadInputRegister1.SflowCylinderB',
      '_ReadInputRegister1.sVolumeTotal',
      '_ReadInputRegister1.sPressureCylinderA',
      '_ReadInputRegister1.sPressureCylinderB',
      '_ReadInputRegister1.sSafetyPressureA_Bar',
      '_ReadInputRegister1.sSafetyPressureB_Bar',
    ],
    'titles': [
      'Out pressure',
      'Total flow',
      'Flow A',
      'Flow B',
      'Total Vol.',
      'Pressure A',
      'Pressure B',
      'Safety P A',
      'Safety P B'
    ],
    'widgetTypes': [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
    ],
  },
  'FLT': {
    'values': [
      'PID_Regulator_4_Pipe1.sStartRegualtion',
      'PID_Regulator_4_Pipe1.sActTemperature',
      'ScaleInputPressure_filterIN.outValue',
      'PID_Regulator_4_Pipe1.sControlPowerOut',
      'PID_Regulator_4_Pipe1.sFinalSetPoint',
      'InletFilterTempMonitor.sActTemperature',
      'PID_Regulator_4_Pipe1.sAuxStepSetpoint',
    ],
    'titles': [
      'Start',
      'Temp',
      'Upstream P',
      'Power out',
      'Setpont',
      'In T',
      'Auxstep'
    ],
    'widgetTypes': [
      0,
      1,
      1,
      3,
      2,
      1,
      1,
    ],
  },
  'BPR': {
    'values': [
      'DuplicateSetPointGradient1.sStartRegualtion',
      'MY_PID_PUMP_REGULATOR_V31.sActValue',
      'MY_PID_PUMP_REGULATOR_V31.ControlValuePercent',
      'DuplicateSetPointGradient1.sFinalSetPoint',
      'DuplicateSetPointGradient1.sGradient_unit_Sec',
      'BackPressureRegulatorTempMonitor.sActTemperature',
    ],
    'titles': [
      'Start',
      'P',
      'Opening',
      'Setpont',
      'Gradient',
      'T',
    ],
    'widgetTypes': [
      0,
      1,
      3,
      2,
      2,
      1,
    ],
  },
};
